const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar
	];
};
self.C3_JsPropNameTable = [
	{Teclado: 0},
	{Fundo: 0},
	{Sólido: 0},
	{PlanoDeFundoEmBlocos: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{Piscar: 0},
	{jogador: 0},
	{caixa: 0},
	{terraesquerda: 0},
	{terrameio: 0},
	{terradireita: 0},
	{tervore: 0},
	{paredeInv: 0},
	{Partículas: 0},
	{caveira: 0},
	{Sprite2: 0},
	{Senóide: 0},
	{inimigo: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite: 0},
	{Tvida: 0},
	{Tcoleta: 0},
	{estado: 0},
	{caveiras: 0},
	{pontos: 0},
	{vidas: 0}
];

self.InstanceType = {
	Teclado: class extends self.IInstance {},
	Fundo: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	jogador: class extends self.ISpriteInstance {},
	caixa: class extends self.ISpriteInstance {},
	terraesquerda: class extends self.ISpriteInstance {},
	terrameio: class extends self.ISpriteInstance {},
	terradireita: class extends self.ISpriteInstance {},
	tervore: class extends self.ISpriteInstance {},
	paredeInv: class extends self.ISpriteInstance {},
	Partículas: class extends self.IParticlesInstance {},
	caveira: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Tvida: class extends self.ITextInstance {},
	Tcoleta: class extends self.ITextInstance {}
}